# Part One


The expedition comes across a peculiar patch of tall trees all planted carefully in a grid. <br>The Elves explain that a previous expedition planted these trees as a reforestation effort. Now, they're curious if this would be a good location for a tree house.

First, determine whether there is enough tree cover here to keep a tree house hidden. <br>To do this, you need to count the number of trees that are visible from outside the grid when looking directly along a row or column.

The Elves have already launched a quadcopter to generate a map with the height of each tree (your puzzle input). For example:<br>

30373<br>
25512<br>
65332<br>
33549<br>
35390<br>
Each tree is represented as a single digit whose value is its height, where 0 is the shortest and 9 is the tallest.<br>

A tree is visible if all of the other trees between it and an edge of the grid are shorter than it. <br>Only consider trees in the same row or column; that is, only look up, down, left, or right from any given tree.

All of the trees around the edge of the grid are visible - since they are already on the edge,<br> there are no trees to block the view. In this example, that only leaves the interior nine trees to consider:

The top-left 5 is visible from the left and top. (It isn't visible from the right or bottom since other trees of height 5 are in the way.)<br>
The top-middle 5 is visible from the top and right.<br>
The top-right 1 is not visible from any direction; for it to be visible, there would need to only be trees of height 0 between it and an edge.<br>
The left-middle 5 is visible, but only from the right.<br>
The center 3 is not visible from any direction; for it to be visible, there would need to be only trees of at most height 2 between it and an edge.<br>
The right-middle 3 is visible from the right.<br>
In the bottom row, the middle 5 is visible, but the 3 and 4 are not.<br>
With 16 trees visible on the edge and another 5 visible in the interior, a total of 21 trees are visible in this arrangement.<br>

Consider your map; how many trees are visible from outside the grid?

In [5]:
import numpy as np

In [90]:
path = "../data/puzzle_8.txt"

In [91]:
with open(path, 'r') as file:
  # Read the contents of the file into a list
  data = file.readlines()

In [92]:
data = [x.replace("\n", "") for x in data]

In [93]:
data

['220311003030020403303010231542401043011111536600504555130543502251500155511123400111142111343321103',
 '112300011121001442140224403450400301003445152052111053406435260452010444113124523432423300221011201',
 '030210134102431134241312344101144221020600111540536441502615542526153154322105541510214043131203100',
 '030101204414334205055102335112246411105640305204415413550445035636165511302522134021011341010042300',
 '231333121332014225332001232453144631040416204620146621036153421503540461150044430323330010312004330',
 '313004122100223501210053543222333364566250521251132261434210544505630145430310211300234000331011113',
 '012412044210025224134545004132405043251661531641253433253260055031356132633542211515154121433313333',
 '223403114014255555503000342035532635342046556443773774444450206405043632662330550032142542032211310',
 '100242031223054535004460205122361434151616645373551326734736364332154140655340554322211502021301422',
 '43140142332541442350303544325464105603746763717675542325123536

In [94]:
arr = np.array([list(map(int, list(x))) for x in data])

In [95]:
arr.shape

(99, 99)

In [96]:
visible = 0
invisible = 0
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if i == 0 or i == arr.shape[0] or j == 0 or j == arr.shape[1]:
            visible += 1
        # check trees above
        elif all(arr[0:i, j] < arr[i, j]):
            visible += 1
        # check trees below
        elif all(arr[i+1:, j] < arr[i, j]):
            visible += 1
        # check trees left
        elif  all(arr[i, :j] < arr[i, j]):
            visible += 1
        elif all(arr[i, j+1:] < arr[i, j]):
            visible += 1
        else:
            invisible += 1

In [97]:
visible

1736

In [98]:
invisible

8065

# Part Two

Content with the amount of tree cover available, the Elves just need to know the best spot to build their tree house: <br>they would like to be able to see a lot of trees.

To measure the viewing distance from a given tree, look up, down, left, and right from that tree; stop if you reach <br>an edge or at the first tree that is the same height or taller than the tree under consideration. (If a tree is right on the edge, at least one of its viewing distances will be zero.)

The Elves don't care about distant trees taller than those found by the rules above; the proposed tree house has<br> large eaves to keep it dry, so they wouldn't be able to see higher than the tree house anyway.

In the example above, consider the middle 5 in the second row:<br>

30373<br>
25512<br>
65332<br>
33549<br>
35390<br>
Looking up, its view is not blocked; it can see 1 tree (of height 3).<br>
Looking left, its view is blocked immediately; it can see only 1 tree (of height 5, right next to it).<br>
Looking right, its view is not blocked; it can see 2 trees.<br>
Looking down, its view is blocked eventually; it can see 2 trees (one of height 3, then the tree of height 5 that blocks its view).<br>
A tree's scenic score is found by multiplying together its viewing distance in each of the four directions. <br>For this tree, this is 4 (found by multiplying 1 * 1 * 2 * 2).

However, you can do even better: consider the tree of height 5 in the middle of the fourth row:<br>

30373<br>
25512<br>
65332<br>
33549<br>
35390<br>
Looking up, its view is blocked at 2 trees (by another tree with a height of 5).<br>
Looking left, its view is not blocked; it can see 2 trees.<br>
Looking down, its view is also not blocked; it can see 1 tree.<br>
Looking right, its view is blocked at 2 trees (by a massive tree of height 9).<br>
This tree's scenic score is 8 (2 * 2 * 1 * 2); this is the ideal spot for the tree house.<br>

Consider each tree on your map. What is the highest scenic score possible for any tree?

In [99]:
scenic_scores = np.zeros_like(arr)
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        # top view
        if i == 0:
            ts = 0
        else:
            ts = 0
            _i = i - 1
            while _i >= 0:
                if arr[_i, j] < arr[i, j]:
                    ts += 1
                    _i -= 1
                else:
                    ts += 1
                    break
        # bottom view
        if i == arr.shape[0]:
            us = 0
        else:
            us = 0
            _i = i + 1
            while _i <= arr.shape[0] - 1:
                if arr[_i, j] < arr[i, j]:
                    us += 1
                    _i += 1
                else:
                    us += 1
                    break
        # left view
        if j == 0:
            ls = 0
        else:
            ls = 0
            _j = j - 1
            while _j >= 0:
                if arr[i, _j] < arr[i, j]:
                    ls += 1
                    _j -= 1
                else:
                    ls += 1
                    break
        # right view
        if j == arr.shape[1]:
            rs = 0
        else:
            rs = 0
            _j = j + 1
            while _j <= arr.shape[1] - 1:
                if arr[i, _j] < arr[i, j]:
                    rs += 1
                    _j += 1
                else:
                    rs += 1
                    break
        score = ts * us * ls * rs
        scenic_scores[i, j] = score

In [100]:
scenic_scores

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  8, ..., 20,  1,  0],
       [ 0, 12,  1, ...,  2,  1,  0],
       ...,
       [ 0,  1,  1, ...,  4,  1,  0],
       [ 0,  2,  8, ...,  1, 35,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [101]:
np.max(scenic_scores)

268800

In [102]:
np.where(scenic_scores==268800)

(array([14]), array([48]))

In [103]:
scenic_scores[:20, 35:50]

array([[     0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0],
       [     6,      1,      1,     10,      9,      2,     78,      1,
            36,      4,      1,     72,     10,      1,      1],
       [     2,      1,     24,      1,    858,      1,      1,      3,
             3,      1,     72,      6,      1,     60,      4],
       [     1,     12,      1,     36,    504,     16,      1,     24,
             1,    360,      2,      1,     54,      8,      1],
       [     2,      1,     32,      1,      8,      1,    384,      2,
             1,      9,    160,      6,      1,      2,     32],
       [    10,     50,     75,    280,      1,     20,      1,     40,
             8,      1,      2,    288,      2,      1,      9],
       [     2,      1,     20,      1,    234,     90,      2,      6,
            10,      1,   1430,      3,      1,      6,    144],
       [   168,      6,      6,      8,  